### ISSUE TITLE
Inexecutable Code output from LLMs

### ISSUE THREAD

**Issue by nsidn98** [SMARTlab-Purdue/SMART-LLM#2]
Hi! Thanks a lot for making the code open-source!

I have been trying to reproduce the results in the paper with gpt-4-1106-preview (compared to 3.5 used in the paper). The code_plans generated by this model seem to be inexecutable when I try executing.

Here is an example of the code_plan generated:

```python
# Assuming we have defined functions for robot actions
# and we have a locking mechanism for the fridge door

fridge_lock = threading.Lock()

def put_item_in_fridge(item):
    GoToObject(item)
    PickupObject(item)
    GoToObject("Fridge")
    fridge_lock.acquire()  # Acquire lock before opening the fridge
    OpenObject("Fridge")
    PutObject(item, "Fridge")
    CloseObject("Fridge")
    fridge_lock.release()  # Release lock after closing the fridge

# Create threads for each task
thread_robot1 = threading.Thread(target=put_item_in_fridge, args=("Bread",))
thread_robot2 = threading.Thread(target=put_item_in_fridge, args=("Lettuce",))

# Start threads
thread_robot1.start()
thread_robot2.start()

# Wait for both threads to complete their current tasks
thread_robot1.join()
thread_robot2.join()

# Now either robot can put tomato in the fridge
thread_robot3 = threading.Thread(target=put_item_in_fridge, args=("Tomato",))
thread_robot3.start()
thread_robot3.join()

# All tasks are done
```

And here is the relevant error when executing the code: `TypeError: GoToObject() missing 1 required positional argument: 'dest_obj'`

How did you ensure that the code generated by the LLM was always executable?

Thanks,
Sid

**Comment by shyamkannan** [comment]
Hi, Sorry I couldn't get back to you earlier, and thank you for your interest in our work. As you pointed out, the code generated was not executable and this is a limitation our work suffers due to the use of LLMs which does not produce consistent results. At the current state of our work, there is no guarantee that the code generated by LLM is always executable.

**Comment by nsidn98** [comment]
Thanks a lot for getting back with your response. Gotcha! Are these failures in executable code generation taken into account in the results section in the paper? Also, was there any study done on the robustness of the code generated? Like the number of times it fails to generate plans, etc.

**Comment by shyamkannan** [comment]
Yeah, in the paper we introduced a metric named "Exec" - Execuatability where we quantified the ratio of the commands generated by the LLM that was executable. We also faced scenarios like what you saw and what Exec is less than 1.0 in some cases (refer to Table 1 in the paper). Due to the nature of the LLMs, it is difficult to generate consistent results and we did experiments repeating the same tasks multiple times, and the variations we observed have been summarized in Table II in the paper.

**Comment by nsidn98** [comment]
Thanks a lot for your reply! That makes sense. Based on my experiments, it seems that SmartLLM's success rate for partially observable environments (scenarios where all the objects it needs to interact with are not visible initially) is quite low. It works quite well when I give in the complete list of interactable objects in the observations. I am guessing this is a limitation of the paper?

**Comment by shyamkannan** [comment]
Yes, we primarily deal with scenarios where we have a complete list of objects. Scenarios where all the objects are not visible initially or the availability of some object is unknown is beyond the scope of this work.

**Comment by nsidn98** [comment]
Thanks a lot for your confirmation!
